source 'https://rubygems.org'

gem 'cane'
gem 'reek'
gem 'rake'
gem 'minitest'
gem 'mrspec'
gem 'pry'
gem 'simplecov'
gem 'byebug'
gem 'sinatra', require: 'sinatra/base'
gem 'shotgun'
gem 'sequel'
gem 'sqlite3'
